"""initial migration.

Revision ID: 0a4da45a92eb
Revises: 
Create Date: 2020-04-23 22:52:20.424560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4da45a92eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=10), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('nim')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
